#!/usr/bin/env bash
#Loop numbers to 100 with diff result multiples 3 and 5

n=1

while (( n <= 100 )); do
    
    if ((( n % 3) == "0")) && ((( $n % 5) == "0")) ;then
	echo FizzBuzz
	((n=n+1))
	elif ((( n % 5)== "0"));then
	    echo Buzz
	    ((n=n+1))
	    elif ((( n % 3)== "0"));then
		echo Fizz
		((n=n+1))
	    
	    
	
    else
	echo $n
	((n+=1))
    fi
    
    
    done
