#!/usr/bin/env bash
#Loop numbers to 100 with diff result multiples 3 and 5

n=1

while (( $n <= 100 )); do
    echo $n
    if ((( $n % 3) == "0")) && ((( $n % 5) != "0")) ;then
	echo Fizz
	((n=n+1))
	if ((( $n % 5)== 0)) && ((($n%3) != 0))
	   echo Buzz
	    
    
	
    else
	
	((n=n+1))
    fi
    
    
    done
