#!/usr/bin/env bash
# Using read and var IFS to tell a story

file="/etc/passwd"
IFS=":"
line=$(read USERNAME PASSWORD UID GROUP_ID USER_ID_INFO HOME_DIRECTORY SHELL) 
#while $line in $file
#do
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $SHELL. $UID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
#done
