#!/usr/bin/env bash
#Loop using if
i=0

while [ $i -lt 10 ];do
      if [ $i -ne 3 -a $i -ne 7 ]; then
      echo 'Best School';
      
      elif [ $i -eq 3 ]; then
    echo 'bad luck'
      else
	  echo 'good luck'
	  fi
      i=$((i+1));
done
      
