#!/usr/bin/env bash
# Infinite loop creates file with pid, catches signal, and removes file/exits:
remover="$(rm -f /var/run/myscript.pid)"

trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command'; remover" SIGTERM
trap "echo 'I hate the kill command'; remover" SIGQUIT


echo $$ >> /var/run/holbertonscript.pid
while (true)
do
    echo 'To infinity and beyond'
        sleep 2
	done