#!/usr/bin/env bash
# Infinite loop creates file with pid, catches signal, and removes file/exits:


trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command';rm -f /var/run/myscript.pid" SIGTERM
trap "echo 'I hate the kill command';rm -f /var/run/myscript.pid)" SIGQUIT


echo "$$" >> /var/run/myscript.pid
while (true)
do
    echo 'To infinity and beyond'
        sleep 2
	done
