#!/usr/bin/env bash
#script that will manage script manage_my_process

argument=$1

if [[ "$argument" == "start" ]];then
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"

elif [[ "$argument" == "stop" ]];then
    echo "manage_my_process stopped"
    echo ""
    pkill -f "manage_my_process"
    echo ""
    rm -f /var/run/my_process.pid

elif [[ "$argument" == "restart" ]];then
    pkill -f "manage_my_process;"
    rm -f /var/run/my_process.pid
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"

else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
    
